### ISSUE TITLE
Beta 1.8-1.6.4 terrain generator support?

### ISSUE THREAD

**Issue by forkiesassds** [b3spectacled/modern-beta-fabric#11]
The b1.8-1.6.4 was the most nostalgic for me, is there going to be the type of generator in this mod, and you might also possibly give users an option to disable the endless oceans too.

**Comment by b3spectacled** [comment]
Hi there, apologies for the late reply.  At this time, I do not have plans to add those terrain generators, partly due to the relative complexity of the fractal biome system (which would have to be re-implemented in full for accuracy), sorry.

**Comment by forkiesassds** [comment]
It would be even harder since 1.18 came out and destroying ALL of the old biome code.
