### ISSUE TITLE
Error upon loading 1.20.2 PaperMC (fabric) server.

### ISSUE THREAD

**Issue by Lambda-Epsilon** [b3spectacled/modern-beta-fabric#110]
System Info:

- Fedora Linux 37 
- Kernel 6.3.8-100
- 64 Gb RAM
- 2x 8C/16T Xeons
- Using latest version of java available for Linux

Error log:

[https://pastebin.com/DvhjKqsK](https://pastebin.com/DvhjKqsK)

This was installed simply by being dropped into the 'plugins' folder of the server. Level-type was set as is illustrated in the guide. If further info is needed for clarification, please let me know.

**Comment by forkiesassds** [comment]
This is a Fabric mod, not a Bukkit plugin...

**Comment by b3spectacled** [comment]
Sorry, as forkie points out, this is not a Bukkit/Paper plug-in.
