### ISSUE TITLE
[1.20.2] World Presets not visible in the Modern Beta World Customization menu

### ISSUE THREAD

**Issue by haroelim** [b3spectacled/modern-beta-fabric#111]
Using 6.4.1+1.20

In the Modern Beta World Customization menu, if I click on the button labeled "World Preset: Beta" the following screen is blank.

It seems that the mod is loading the preset list, it is just not displaying the list correctly, as I am able to click on different parts of the screen and use a different preset

I've attached a screenshot of what I see. I am not running any other mods.

![20231019 Modern Beta Preset Selection Screen Blank](https://github.com/b3spectacled/modern-beta-fabric/assets/75040453/2efe1b0c-ed39-473e-be05-5c5e8ba002b7)

**Comment by b3spectacled** [comment]
Thanks, I can reproduce the issue. Will take a look.

**Comment by b3spectacled** [comment]
Fixed as of 6.5+1.20.2. Thank you.
