### ISSUE TITLE
Biome colors get messed up on Vanilla Multiplayer servers

### ISSUE THREAD

**Issue by forkiesassds** [b3spectacled/modern-beta-fabric#12]
On Vanilla Multiplayer servers all biome colors get messed up that they just don't match up to the vanilla biome colors.

With mod:
![2020-12-07_12 47 35](https://user-images.githubusercontent.com/54495659/101342686-9963db80-388b-11eb-86df-593239c7e5b6.png)

Without mod:
![2020-12-07_12 49 17](https://user-images.githubusercontent.com/54495659/101342843-cca66a80-388b-11eb-9269-9a0427b780bf.png)

The server is running on Paper 1.16.4.

**Comment by b3spectacled** [comment]
This is intended so you can use Beta biome colors on servers with Beta terrain.  There is an option to turn off the Beta colors, either through Mod Menu or the config file in .minecraft/config.

**Comment by forkiesassds** [comment]
> 
> 
> This is intended so you can use Beta biome colors on servers with Beta terrain. There is an option to turn off the Beta colors, either through Mod Menu or the config file in .minecraft/config.

Oh.
