### ISSUE TITLE
pre-1.14 villages but with chests?

### ISSUE THREAD

**Issue by Optimuspr04091** [b3spectacled/modern-beta-fabric#129]
is it possible to add this?
![image_2024-02-11_224906058](https://github.com/b3spectacled/modern-beta-fabric/assets/88454400/cf7c9188-7c57-46ea-85c7-ca7d42e11a94)

**Comment by Daralexen05** [comment]
There is a datapack I use that adds old villages with workstations. However, no chests besides the Blacksmith.
