### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by MattsCurrie** [b3spectacled/modern-beta-fabric#13]
Hi! I really love this mod and I want to know how it works and how I can support it.

**Comment by MattsCurrie** [comment]
I don't have any experience writing documentation, but I would be happy to learn how.

**Comment by b3spectacled** [comment]
Hiya, thanks very much for the support.  To be honest, I am not a great documentation writer myself, so I don't think I could advise well on it.

Do feel free to fork and fool around with the mod.  If you have questions, you can reach me on Discord at b3spectacled_#7504.
