### ISSUE TITLE
Suggestion | Beta mechanics

### ISSUE THREAD

**Issue by Simple205** [b3spectacled/modern-beta-fabric#17]
I've wanted to use fabric for a classic experience for the longest time because of your mods but because of another mod on forge that restores beta mechanics and has tons of configuration options I couldn't give that up. I don't know how to write code or make mods but can you make a fully fledged configurable mod that restores beta mechanics?

**Configurable options include**

- Remove hunger
- Attack cooldown and sweeping edge (also gets rid of op axe damage)
- Food stack (disabling food stack enables instant eating from beta)
- No pull bow
- Disable sprint
- Old main menu

I don't know the chances of this becoming a reality especially because of another mod out there that does the exact same thing on forge but if it does I'm definitely going to fabric.

**Comment by b3spectacled** [comment]
I appreciate the suggestion, and I definitely would like to see a mod like this.  Unfortunately, I am a little too busy to be the one to write it, sorry!
