### ISSUE TITLE
[Issue] It crashes (or doesn't progress) when making new worlds

### ISSUE THREAD

**Issue by asteroidb12** [b3spectacled/modern-beta-fabric#19]
This is a great mod, however i find this issue:
Whenever I make a new world, it either crashes or stops preparing spawn point. I tested this on Beta, one of the Indevs and Infdev type

Here's the mod list:
![image](https://user-images.githubusercontent.com/68461874/109133410-d660a100-7709-11eb-8a9e-8da05e5c805c.png)

Here's one crash report and a log file:
[crash-2021-02-24_22.02.15-server.txt](https://github.com/b3spectacled/modern-beta-fabric/files/6041958/crash-2021-02-24_22.02.15-server.txt)
[latest.log](https://github.com/b3spectacled/modern-beta-fabric/files/6041959/latest.log)

Note: I had to use Task Manager because it hasn't progressed for a long time

**Comment by b3spectacled** [comment]
Does the issue persist when you toggle the 'Generate Oceans' option to off?

**Comment by b3spectacled** [comment]
I believe I've narrowed down the issue to Hydrogen; please remove that mod and test again, please.

**Comment by asteroidb12** [comment]
Removed Hydrogen, It has no major effect, it stops at 100% (Used Task Manager since it stops there)

Logs:
[2021-02-26-3.log](https://github.com/b3spectacled/modern-beta-fabric/files/6053910/2021-02-26-3.log)
[latest.log](https://github.com/b3spectacled/modern-beta-fabric/files/6053911/latest.log)

**Comment by b3spectacled** [comment]
Can you zip up and attach your mod folder?  Would appreciate it very much.

**Comment by asteroidb12** [comment]
(big file more than 10MB so i had to use drive)
here: https://drive.google.com/file/d/1-DZbUqJzm69BMohp5ZsiJ4CM6oPuC6WY/view?usp=sharing

**Comment by b3spectacled** [comment]
Thank you.  It's a little strange, I initially encountered the issue on the first world creation, removed some mods, re-added them, and now am unable to reproduce it.

**Comment by asteroidb12** [comment]
Small update: 
downgrading it to 1.0.6 seems to make it work for Beta, however generating an infdev with modded/vanilla biomes and pyramid doesn't seem to work somehow,

Infdev log:
[2021-02-27-7.log](https://github.com/b3spectacled/modern-beta-fabric/files/6055847/2021-02-27-7.log)
Beta log:
[latest.log](https://github.com/b3spectacled/modern-beta-fabric/files/6055864/latest.log)

Note: removed mods which cause the game to crash when starting.
