### ISSUE TITLE
Ore generation seems incorrect in Beta world-type

### ISSUE THREAD

**Issue by L2KSolkov** [b3spectacled/modern-beta-fabric#21]
Ore generation doesn't seem to be correct when using "Beta 1.7.3" world-type with either Beta or Classic generation setting. 

Using version 1.0.7 of the mod. 
Beta 1.7.3 Generation:
![2021-02-27_10 29 26](https://user-images.githubusercontent.com/7198881/109396653-6e67b180-78e7-11eb-8d09-5e9d25504685.png)

1.16.5 Generation

![2021-02-27_10 33 23](https://user-images.githubusercontent.com/7198881/109396675-96571500-78e7-11eb-9e07-e2fd2369da45.png)
![2021-02-27_10 33 38](https://user-images.githubusercontent.com/7198881/109396680-9c4cf600-78e7-11eb-9508-c554cd4e157b.png)

**Comment by L2KSolkov** [comment]
Would probably help if I included the seed. Whoops.

108181935

**Comment by b3spectacled** [comment]
This is intended, all world types use the vanilla feature (ores, trees, small lakes, plants, etc.) populators when possible (excluding a few things like big trees or clay).  Sorry, I will make this more clear on the project description page or something.

Having exact feature placement is possible, but depends on me porting every single feature exactly as they are in the Beta 1.7.3 source and then generating them in the exact same order.  It's a lot of work, and then compounded if I were to do the same for the other world types.
