### ISSUE TITLE
Suggestion: Old villages

### ISSUE THREAD

**Issue by Simple205** [b3spectacled/modern-beta-fabric#22]
Pre 1.14 villages? after I saw the ocean shrine I thought it would be very cool to have an option to generate original villages with gravel paths and all.

**Comment by b3spectacled** [comment]
This is a bit of a late reply, sorry, but this would be possible for the most part with a structure data pack.  That said, it would be time-consuming to replace all of the structures, and it's out of scope for the mod IMO.

**Comment by Simple205** [comment]
would you consider doing it as a separate data pack/ mod if you found time to do it?
