### ISSUE TITLE
(Suggestion:) Classic World Generator

### ISSUE THREAD

**Issue by StereoMadnessss** [b3spectacled/modern-beta-fabric#25]
The type of world generation types that I want are 0.0.23a_01, 0.0.14a, and 0.30 The world generator name is "Classic" in modern beta

**Comment by forkiesassds** [comment]
If I'm correct Indev had a mostly similar generator to 0.30 if you use the inland type. And if you use the generator from Infdev 227, you can have the 0.30 terrain generator but infinite if you enable certain options.

**Comment by StereoMadnessss** [comment]
could there be 0.0.14a terrain?

**Comment by forkiesassds** [comment]
> 
> 
> could there be 0.0.14a terrain?

Yes, and 0.0.23a_01 has different terrain gen than 0.24.

**Comment by b3spectacled** [comment]
I will be adding 0.30, but in general, I'm a little hesitant to add terrain generators from this period of Minecraft, since it's difficult to verify correctness.  All I can do for now is to re-implement the terrain gen algorithms to the best of my ability and just see if it looks 'right'.
