### ISSUE TITLE
Infdev 20100227 has imprecise generation

### ISSUE THREAD

**Issue by bugmancx** [b3spectacled/modern-beta-fabric#28]
Generate World Type: Infdev 20100227

Infdev 20100227 world generation erroneously generates with trees and grass in certain places, which did not exist in this version's terrain.

Additionally, it generates with caves which is incorrect as this terrain did not contain any caves (perhaps that should be configurable?)

[Love the mod btw!]

**Comment by b3spectacled** [comment]
Hi there,

This mod doesn't aim to make any gameplay changes.  Sparse amounts of trees and tall grass are present to make the world type survival-friendly.  You'll also find tall grass generating in the Alpha 1.1.2_01 and other Infdev world types as well.

FWIW, I'm split on it, but I want players to be able to do something with these older world generation types.  For the 1.16 version of the mod, I do supply data pack files so they can add/remove biome features like the trees if they wish.

I appreciate the feedback. (And am a fan of MC: The Journey! c:)
