### ISSUE TITLE
[1.16.3] Does not generate pack.png seed correctly

### ISSUE THREAD

**Issue by Jarfeh** [b3spectacled/modern-beta-fabric#3]
Using the pack.png seed, instead of it generating the iconic hill, it generates this instead:
![2020-10-09_21 22 32](https://user-images.githubusercontent.com/58902941/95645606-b2136900-0a75-11eb-836b-caec63432bec.png)
using alpha world type

**Comment by b3spectacled** [comment]
The Alpha world type uses the Alpha 1.1.2_01 terrain generator, which is different than the one used from Alpha 1.2 to Beta 1.7.3.  Use the Beta world type.

**Comment by Jarfeh** [comment]
That was it, thanks!
