### ISSUE TITLE
Cave generation occasionally gets cut off at chunk borders.

### ISSUE THREAD

**Issue by FrozenDragon0** [b3spectacled/modern-beta-fabric#36]
So this is a bug that is present in the original beta versions of the game, essentially caves will sometimes get cut off by a chunk when generating resulting in a unnatural stone wall in caves.

Mod settings used:

Beta 1.7.3 gen, no other settings changed.

Some screenshots here:

![2021-07-12_10 03 19](https://user-images.githubusercontent.com/18079316/125220180-da780e80-e2f8-11eb-858d-72845da0b3da.png)
 
![2021-07-12_10 00 10](https://user-images.githubusercontent.com/18079316/125220223-ea8fee00-e2f8-11eb-943b-42a2d4c4d5bf.png)

![2021-07-12_10 00 41](https://user-images.githubusercontent.com/18079316/125220255-f976a080-e2f8-11eb-91b9-84ee57bf1dfa.png)

![2021-07-12_10 03 42](https://user-images.githubusercontent.com/18079316/125220267-009dae80-e2f9-11eb-856c-8755be5ec13a.png)

This last screenshot is the most notable one and definitely part of the bug as caves are not supposed to generate with a perfect wall like that.

This bug also affects the Alpha generation.

![2021-07-12_10 10 30](https://user-images.githubusercontent.com/18079316/125220498-70ac3480-e2f9-11eb-8de3-73db1e2340e7.png)

**Comment by b3spectacled** [comment]
Can you provide examples where this does not happen for seeds in the respective original versions (Beta or Alpha)?  If it's a generation quirk that is present in the original versions, then I'm inclined to leave it as-is for accuracy.

**Comment by FrozenDragon0** [comment]
@b3spectacled It's consistent across both the mod and original gen regardless of the seed.

Beta 1.7.3 screenshot seed Glacier.
![2021-08-26_15 33 16](https://user-images.githubusercontent.com/18079316/130921450-95ee33f3-3fe9-4a5a-91ae-31d4ffd6ddf0.png)

Modern Beta screenshot same seed same location. Coords: X 75, Y 17, Z 272.
![2021-08-26_15 33 28](https://user-images.githubusercontent.com/18079316/130921507-14ebfb3b-b4aa-40e6-8b8a-77039169d9b6.png)

Perhaps a config option can be added that fixes this bug depending if it's enabled or not? That's Just my suggestion if you want to leave it as is for accuracy.

**Comment by FrozenDragon0** [comment]
I'm guessing a config option to fix this bug won't be added?

**Comment by b3spectacled** [comment]
Probably not, I've yet to identify a fix for this.

**Comment by FrozenDragon0** [comment]
@b3spectacled I do remember I had a mod for the original Beta 1.7.3 that backported Beta 1.8's Ravine generation but it also backported the fix for this bug from Beta 1.8. I could send you the class files on here and perhaps you could look at those to try find a fix?

**Comment by Delfite** [comment]
> @b3spectacled I do remember I had a mod for the original Beta 1.7.3 that backported Beta 1.8's Ravine generation but it also backported the fix for this bug from Beta 1.8. I could send you the class files on here and perhaps you could look at those to try find a fix?

You should post it regardless, not like anyone's gonna stop you.

**Comment by b3spectacled** [comment]
This took a bit to say the least, but the Beta 1.8 cave RNG fix is now backported for release 6.3+1.19.4.
