### ISSUE TITLE
Structure issues on skylands

### ISSUE THREAD

**Issue by Monster-Zer0** [b3spectacled/modern-beta-fabric#37]
on the skylands generation. I have noticed that a lot of structures do not generate. Including very important ones.. like strongholds and villages. not sure if that's just a height generation setting or if you decided to remove most structures from generating.

**Comment by b3spectacled** [comment]
Please provide more information. Can you provide:
- MC and mod version
- Biome type
- World seed, if possible

The Skylands world type does not restrict structure generation in any way, if a particular biome has a structure, then it will try to generate it.
