### ISSUE TITLE
Certain biomes have lighting bugs

### ISSUE THREAD

**Issue by ghost** [b3spectacled/modern-beta-fabric#41]
Some biomes (so far I've noticed it in the Savanna although there could be others) have major lighting issues.
See attached screenshot:

![2021-08-08_18 32 21](https://user-images.githubusercontent.com/41847745/128647607-a68d801a-1322-4f80-92d4-d720836a27eb.png)

**Comment by b3spectacled** [comment]
This appears to be an issue with the biome colormap in the resource pack that you're using.

Modern Beta restores biome color sampling of the entire grass/foliage colormap.  Vanilla Minecraft only samples a handful of pixels, so understandably most resource packs only account for those specific points.  This means though that if the colormap looks like this, then it won't work:

![Optifine Colormap Template](https://i.imgur.com/6MCBfgD.png)

The colormap needs to completely filled like so:

![Vanilla Colormap](https://i.imgur.com/J5Lyw28.png)

EDIT: As a workaround, you can toggle the Render Beta Biome Colors option, before opening the world.  This will make the mod revert to the vanilla biome tinting behavior, though you of course won't get the variety in biome colors.

**Comment by ghost** [comment]
Oh, apparently more than one of the resource packs I was using had color maps and I didn't realize. Deleting the textures/colormaps folder from the packs fixed it. Thank you!
