### ISSUE TITLE
[Request] Port the world generation aspects into a Spigot world gen plugin

### ISSUE THREAD

**Issue by loudcricketts** [b3spectacled/modern-beta-fabric#43]
See title.
This mod appears to be one of a kind for the amount of options it has, and if it becomes available for spigot/paper servers then that will be amazing.

**Comment by b3spectacled** [comment]
Thank you for the suggestion.  Unfortunately I do not have the time for ports for any other modloader or plugin system.  People are free to port or create something based on this mod though.
