### ISSUE TITLE
Suggestion: 2d items

### ISSUE THREAD

**Issue by JimmyHarmel** [b3spectacled/modern-beta-fabric#44]
I think It would be neat to add sprite rendered items back into the game for a bit of nostalgia as seeing 3d spinning items in an indev world I'm working on can sort of ruin the vibe for me.
![2d itns](https://user-images.githubusercontent.com/86896069/131231590-b78dc580-2de9-44c3-8611-6a2ba956ffc5.png)

**Comment by b3spectacled** [comment]
Thanks for the suggestion, it's a bit outside of the scope of the mod though; I am willing to consider rendering additions if it serves the world generation.  Maybe in a separate mod.
