### ISSUE TITLE
[Suggestion] Replace original icon with a compressed one.

### ISSUE THREAD

**Issue by K0-RR** [b3spectacled/modern-beta-fabric#45]
The current icon is big, I tried to compress it losslessly but the difference wasn't as big as in other mods. Here is a lossy compressed version for you to compare and replace if you want. You can move the original one to the repository root as a backup.

![icon](https://user-images.githubusercontent.com/43277609/136811837-ec9acb5d-98b7-4bd9-bc89-232817cc1492.png)

**Comment by b3spectacled** [comment]
I've just updated the mod with an icon that is a bit smaller than yours.  Appreciate all of your suggestions thus far!
