### ISSUE TITLE
[1.17.1] PE v0.6.0 generation crashes game

### ISSUE THREAD

**Issue by Delfite** [b3spectacled/modern-beta-fabric#47]
MC Version: 1.17.1
Fabric Version: 0.11.6
Mod Version: modern-beta-fabric-2.6+1.17.1.jar

Description:
The new PE generation option crashes the game with and without settings being changed.

How to recreate:
Step 1. Create a new world with the Modern Beta world type
Step 2. Click "Customize"
Step 3. Select the "PE v0.6.0" option
Step 4. Generate the world
Step 5. Hard-crash to launcher with the following error:
```
The game crashed whilst exception initializing level
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_5873.<init>(net.minecraft.class_2794, net.minecraft.class_5539)'
Exit Code: -1
```

Crashlog: https://pastebin.com/xSR2kFtk

Please fix this soon, I really liked the old Pocket Edition terrain and want it back desperately ;-;

**Comment by Delfite** [comment]
Nope nevermind turns out this happens with ALL of the mod's world types.

**Comment by b3spectacled** [comment]
You're playing on Minecraft 1.17. This version of the mod only supports 1.17.1 (I did mistakenly mark 1.17 as being compatible on the CF download, so apologies if that misled you).  Please update to Fabric Loader for 1.17.1.

**Comment by Delfite** [comment]
Oh right, forgot to update my modpack. Thanks for telling me since that single digit is hard to notice.
