### ISSUE TITLE
[Feature Request] Customize Text for Game Version Render on Top of the Screen

### ISSUE THREAD

**Issue by StereoMadnessss** [b3spectacled/modern-beta-fabric#48]
This as a feature would be nice because some people want the classic feel of the game. For example if you love infdev then you can set the text on the top of the screen to be "Minecraft Infdev" instead of 1.17.1. **THIS IS OPTIONAL** if you want to add it into the mod then in my opinion, it would be a welcome addition. But it is your choice. Btw thank you for reading b3spectacled if you saw this.

**Comment by b3spectacled** [comment]
Thank you for the suggestion.  I am on the fence about allowing this; I don't want to mislead, and I want it to be clear that these terrain generators are still ports to a modern version of Minecraft.  I try my best for the base terrain generators to be accurate to their respective versions, but I may make mistakes, and other aspects of world generation like feature and structure decoration are not accurate for various reasons.  I don't want people to see screenshots or whatnot of my mod and get the impression that some quirk or error are representative of some older version of the game.

I still appreciate the suggestion and may still consider it, if there's a really good reason for it.  This mod is a classic Minecraft terrain generator mod first and classic Minecraft gameplay/experience simulator second (or not at all). People who want the latter should probably just play those versions.

**Comment by Delfite** [comment]
> Thank you for the suggestion. I am on the fence about allowing this; I don't want to mislead, and I want it to be clear that these terrain generators are still ports to a modern version of Minecraft. I try my best for the base terrain generators to be accurate to their respective versions, but I may make mistakes, and other aspects of world generation like feature and structure decoration are not accurate for various reasons. I don't want people to see screenshots or whatnot of my mod and get the impression that some quirk or error are representative of some older version of the game.
> 
> I still appreciate the suggestion and may still consider it, if there's a really good reason for it. This mod is a classic Minecraft terrain generator mod first and classic Minecraft gameplay/experience simulator second (or not at all). People who want the latter should probably just play those versions.

You seem to be bad at cleaning up your currently open issues (aka closing them once a response/solution is given and is proven to work)

**Comment by b3spectacled** [comment]
Closing as I just learned about Nostalgic Tweaks, which looks to do this (and many other things)! https://github.com/Adrenix/Nostalgic-Tweaks
