### ISSUE TITLE
How to generate modern biomes?

### ISSUE THREAD

**Issue by helpimnotdrowning** [b3spectacled/modern-beta-fabric#5]
I cant get the Beta generator to generate modern biomes, is it possible to generate beta and modern biomes together like in the datapack?

**Comment by b3spectacled** [comment]
Not right now.  May add this in a future update.

**Comment by b3spectacled** [comment]
Hiya, so I'll be adding vanilla biome mappings for Beta worlds in the next update.  Unfortunately, the current implementation seems to cause crashes on older worlds, so hang tight while I look into it.

**Comment by b3spectacled** [comment]
Added in release v0.8!
