### ISSUE TITLE
Crash when trying to select Modern Beta in world creation settings (1.18.1 only)

### ISSUE THREAD

**Issue by AViewFromTheTop** [b3spectacled/modern-beta-fabric#50]
When clicking the world type, when the game would normally show "Modern beta," the game instead crashes.
This only happens in 1.18.1 - 1.18 is fine,
Here's the crash log: [crash-2021-12-11_16.50.18-client.txt](https://github.com/b3spectacled/modern-beta-fabric/files/7697793/crash-2021-12-11_16.50.18-client.txt)
 I've also tested this with only Modern Beta and no other mods, and this issue still occurs with the same crash details.

**Comment by b3spectacled** [comment]
The 1.18/1.18.1 version is still unreleased and under development.  The mod is going through some decent reworks, so issues are bound to crop up.

EDIT: Will leave this open for now though, I do anticipate issues with config files from older versions of the mod.

**Comment by AViewFromTheTop** [comment]
> The 1.18/1.18.1 version is still unreleased and under development. The mod is going through some decent reworks, so issues are bound to crop up.
> 
> EDIT: Will leave this open for now though, I do anticipate issues with config files from older versions of the mod.

Quick update, I downloaded the source code and migrated the mappings to 1.18.1, it works perfectly now! (I probably should've done that before submitting this)
I don't know if you want this issue closed due to your prior comment, but at least we know it's a really simple fix now! :)
Edit: Ok I'm dumb. This only fixes it inside the development thing (VS Code, IntelliJ, Eclipse, etc.)
It still crashes the game with only Fabric API and Cloth Config outside of those programs.

**Comment by AViewFromTheTop** [comment]
Ok I'm dumb. This only fixes it inside the development thing (VS Code, IntelliJ, Eclipse, etc.)
It still crashes the game with only Fabric API and Cloth Config outside of the development things.
