### ISSUE TITLE
Crash Upon Trying To Select "Modern beta" In World Customization

### ISSUE THREAD

**Issue by AViewFromTheTop** [b3spectacled/modern-beta-fabric#51]
Hello! The bug where the game crashes upon trying to get to Modern Beta in the World Customization menu still persists for me in the full release.
I've tested with strictly Fabric API, Cloth Config, Mod Menu, and Modern Beta, and this crash persists. No matter what mods I use, the crash still happens. 
Crash log deobfuscated by NotEnoughCrashes: [crash-2021-12-20_09.01.33-client.txt](https://github.com/b3spectacled/modern-beta-fabric/files/7745871/crash-2021-12-20_09.01.33-client.txt)
I haven't seen anyone come across this bug, so I don't know what exactly the problem could be;
I've used Fabric 12.11 and 12.12, I'm using the correct Fabric API, I've tested with the versions of ModMenu and Cloth Config that are needed as described by gradle.properties, I've tested with only this mod and its dependencies, and the same issue occurs.
Just to note, I've tested this with the latest uploaded artifacts and the release on CurseForge, both do the same thing.

**Comment by b3spectacled** [comment]
Can you try deleting the config folder so it can regenerate with default configs?

**Comment by AViewFromTheTop** [comment]
That seems to fix it! Thank you so much!!
