### ISSUE TITLE
Azalea Trees Generate in Water in a1.1.2_01 worlds with ocean biomes turned off

### ISSUE THREAD

**Issue by StereoMadnessss** [b3spectacled/modern-beta-fabric#52]
For some reason azalea trees generate in a weird way in a1.1.2_01 worlds. This is a weird one because it might be a bug or an intended feature. Screenshot:
![2022-01-16_21 52 48](https://user-images.githubusercontent.com/77188051/149715075-12f6a444-2dc8-4a3a-9e58-8806f8d4918b.png)
Seed: -1557177954440650941
Coords: -68 70 139

**Comment by b3spectacled** [comment]
I believe that's how vanilla Azalea trees generate.
