### ISSUE TITLE
[Feature request] Xbox 360 Legacy edition TU1

### ISSUE THREAD

**Issue by wecome42** [b3spectacled/modern-beta-fabric#55]
Add Xbox 360 TU1 as a generator since being in a limited world can be interesting and feels cosy, it also brings back nostalgia playing 360 so this would fit the plugin. Since TU1 terrain is the same as Beta 1.7.3 it could be easy to implement, you would just need to generate infinite flat ocean after 432 blocks out and smooth the edge to the infinite ocean like it's done on 360. But you'll need to make sure they are exactly the same terrain shape smoothing on the edge.

Hope you like my suggestion.

**Comment by ruttn** [comment]
Rather late to this, but yeah this would be pretty cool! Would also be useful for friend groups etc who want to create a single "island" to play on. Maybe a configurable size option for Xbox One/PS4-esque worlds?

**Comment by ivx0** [comment]
This would be really cool

**Comment by EmqsaGit** [comment]
Maybe all TUs generations, and maybe *even* Xbox One's EUs would be a good idea too.

**Comment by DarianLStephens** [comment]
I'd like to see that, too.
I quite enjoyed playing on the 360, and the limited map size makes it feel a lot more connected in multiplayer. A much more natural border than the literal world border.
I would like to see the border distance be customizable, though.

**Comment by b3spectacled** [comment]
I know this is an older thread, but please look forward to the upcoming 1.19.4 update. =)

**Comment by DarianLStephens** [comment]
Oh dang, are they doing it? I've _love_ to see that. Especially if it is this original version of the terrain.

**Comment by b3spectacled** [comment]
Well, I don't know exactly how it's done in the old TU editions, but it should look very close.

**Comment by DarianLStephens** [comment]
It was basically alpha or beta 1.7 terrain, but it dropped off quickly around the edges of a square map in to the ocean.
There was also a sort of invisible 'world border' past the edge, and I remember that, while the inner playable area of the map dropped down on the edges, the inaccessible outside world past that was flat, and often several blocks higher than the lowest part of the playable area, so you could see this wall underwater.

**Comment by b3spectacled** [comment]
Yes, I'm aware of how it 'looks', I meant on a technical level. As such, I wouldn't be able to guarantee 100% accuracy with the generation.

**Comment by b3spectacled** [comment]
A world preset emulating the old TU world generation has been added with 6.0+1.19.4 as an alt world preset called "Beta Xbox Legacy".

**Comment by DarianLStephens** [comment]
I don't know if it's just me, but I don't see where this option is.
Is it part of the 'Modern Beta' option? I go in to 'Customize', but cycling through the option at the top doesn't have anything which says 'Xbox'.

**Comment by DarianLStephens** [comment]
Ah, I found it! You have to actually hold Alt while clicking the button to reach these settings.

Although, it seems the world can't be displayed on a single map anymore. Is there any way to adjust the 'map center' so it can show the whole island, or adjust the position of the island itself so it lines up with the map?
