### ISSUE TITLE
Crash when changing biome assignments

### ISSUE THREAD

**Issue by gtrxAC** [b3spectacled/modern-beta-fabric#58]
Steps to reproduce:
- create new world
- world type modern beta
- customize
- biome settings
- change Swampland -> Land to "Swamp" or Shrubland -> Land to "Desert"
- press Done twice
It shows "saving world" then crashes.
Any other biome changes work fine, even changing Swampland or Shrubland to something else works.

[crash_swamp.txt](https://github.com/b3spectacled/modern-beta-fabric/files/8491357/crash_swamp.txt)
[crash_desert.txt](https://github.com/b3spectacled/modern-beta-fabric/files/8491358/crash_desert.txt)

**Comment by b3spectacled** [comment]
Fixed with 3.0.4 and 4.0.0. Thanks!
