### ISSUE TITLE
[Feature Request] Cave Generation types based off MC versions

### ISSUE THREAD

**Issue by Zockerhopper** [b3spectacled/modern-beta-fabric#59]
So there is this dude called TheMasterCaver, in the Forums, and as I understand he only plays 1.6.4 because the density and frequency of caves in that version was much greater. There is this now defunct Mod called "Swiss Cheese Caves" but as it is no longer mantained or updated I thereby call on you to add an Option for us to pick what Cave Generation we want (1.6 - Era; 1.7 - Era and 1.18). Accompanying that Mineshafts were 2.5 times more common in the 1.6 - Era so I'll clump both of them together.

**Comment by b3spectacled** [comment]
Not planned. You can configure cave and structure (e.g. mineshafts) generation by data packs anyway.
