### ISSUE TITLE
Structures generate with incorrect height

### ISSUE THREAD

**Issue by b3spectacled** [b3spectacled/modern-beta-fabric#6]
Structures like villages may sometimes generate with incorrectly sampled heights, causing them to generate on top of tall monoliths.

If you have instances of this occurring, please post below with seed and coordinates.  Thank you!

**Comment by Arenovas** [comment]
These aren't on monoliths, but they are floating though. Using the Skylands world generation, several buildings of a village end up floating in the air, and just over the hill there's a blacksmith buried in the hill along with a floating house. The seed is 1834910453 and the coordinates are -8 71 499. And I am on version 0.8.2 of the mod.

**Comment by b3spectacled** [comment]
I didn't really intend to fix the problem for the Skylands world type, but I think I have a nice solution for the next update!

**Comment by b3spectacled** [comment]
Does not appear to be a problem any longer.
