### ISSUE TITLE
Pre-1.18 generation?

### ISSUE THREAD

**Issue by clmc99** [b3spectacled/modern-beta-fabric#61]
Will Modern Beta ever have an option for the pre-1.18 (1.14-1.17 I believe) world generation? A lot of biome mods (BYG comes to mind but that's just the one I'm most familiar with) were really screwed by 1.18, and I'd love to see them with new blocks and mobs but old terrain gen. Not really an issue, but posting this here because I don't see a Discord link (if there is and it's more appropriate to put this there, let me know!)

**Comment by forkiesassds** [comment]
Probably never, since of the complexity of the b1.8-1.17 biome gen system. Also the values used for biomes in 1.18 are not compatible with the b1.8-1.17 biome system.

**Comment by clmc99** [comment]
Sad. Thanks for the reply!
