### ISSUE TITLE
(Suggestion) Option to change sea level

### ISSUE THREAD

**Issue by NinCollin** [b3spectacled/modern-beta-fabric#65]
I've been messing around with this mod to pregenerate a range of chunks from a variety of different generators (by changing the generator specified in the config and in level.dat) and it works spectacularly well, but one glaring limitation is that some generators have different sea levels (I believe 64, 63, and 62 are the various levels, but I may be mistaken) and this isn't something that can be easily smoothed out.

While I do understand that my usage scenario may be unsupported and/or niche, it would be beneficial to have some sort of option (whether global or generator specific) to either manually change the sea level, or even just have it match the modern sea level of 62.

**Comment by b3spectacled** [comment]
You can change the sea level via datapack.
