### ISSUE TITLE
Add back vanilla biome type option

### ISSUE THREAD

**Issue by forkiesassds** [b3spectacled/modern-beta-fabric#66]
I don't really want beta biomes in my beta generation, however I would really want vanilla biomes to generate in the beta terrain however the option was removed in 5.0.0 and I would love it to be added back. Not sure how would it adapt the biome generation ranges to beta's 2d biome map to adapt to the terrain.

**Comment by b3spectacled** [comment]
Use the new 'voronoi' biome option; you can customize it to create a biome map with whichever biomes you like.

Removing the vanilla biome option was a concession I made to myself to get any update out at all. Trying to get the vanilla biome source to work with the mod was extremely frustrating and hacky, I'd rather just not deal with it.

EDIT: As an example, here's a template for using vanilla biomes with the voronoi biome type.

<code>"voronoiPoints": [
  {  
    "biome": "minecraft:snowy_plains",
    "oceanBiome": "minecraft:frozen_ocean",
    "deepOceanBiome": "minecraft:frozen_ocean",
    "temp": 0.0,
    "rain": 0.0
  },
  {
    "biome": "minecraft:snowy_taiga",
    "oceanBiome": "minecraft:frozen_ocean",
    "deepOceanBiome": "minecraft:frozen_ocean",
    "temp": 0.0,
    "rain": 0.5
  },
  {
    "biome": "minecraft:swamp",
    "oceanBiome": "minecraft:cold_ocean",
    "deepOceanBiome": "minecraft:cold_ocean",
    "temp": 0.0,
    "rain": 1.0
  },
  {
    "biome": "minecraft:savanna",
    "oceanBiome": "minecraft:ocean",
    "deepOceanBiome": "minecraft:ocean",
    "temp": 0.5,
    "rain": 0.0
  },
  {
    "biome": "minecraft:forest",
    "oceanBiome": "minecraft:ocean",
    "deepOceanBiome": "minecraft:ocean",
    "temp": 0.5,
    "rain": 0.5
  },
  {
    "biome": "minecraft:plains",
    "oceanBiome": "minecraft:ocean",
    "deepOceanBiome": "minecraft:ocean",
    "temp": 0.5,
    "rain": 1.0
  },
  {
    "biome": "minecraft:desert",
    "oceanBiome": "minecraft:lukewarm_ocean",
    "deepOceanBiome": "minecraft:lukewarm_ocean",
    "temp": 1.0,
    "rain": 0.0
  },
  {
    "biome": "minecraft:dark_forest",
    "oceanBiome": "minecraft:lukewarm_ocean",
    "deepOceanBiome": "minecraft:lukewarm_ocean",
    "temp": 1.0,
    "rain": 0.5
  },
  {
    "biome": "minecraft:jungle",
    "oceanBiome": "minecraft:warm_ocean",
    "deepOceanBiome": "minecraft:warm_ocean",
    "temp": 1.0,
    "rain": 1.0
  }
]</code>

**Comment by b3spectacled** [comment]
Added a 'Beta Vanilla' world preset as of 6.2+1.19.4, which generates most current vanilla biomes.
