### ISSUE TITLE
Modern Beta simply isn't showing the customize button when making a world.

### ISSUE THREAD

**Issue by Fuffley** [b3spectacled/modern-beta-fabric#69]

**Comment by Fuffley** [comment]
I am on 1.19.3 for reference.

**Comment by b3spectacled** [comment]
There isn't a customize button, change world type through a data pack: https://github.com/b3spectacled/modern-beta-fabric-datapacks

Alternatively, wait until the 1.19.4 version of the mod, I plan to re-add it.

**Comment by b3spectacled** [comment]
Re-added the in-game world customization GUI with 6.0+1.19.4.
