### ISSUE TITLE
Add Beta 1.8 to 1.6.4 World Generator

### ISSUE THREAD

**Issue by StereoMadnessss** [b3spectacled/modern-beta-fabric#70]
The latest mod that has done this is from 1.7.10, and since Beta 1.8 is still Beta, I think that it could be a welcome addition to Modern Beta for the people who would like to have it.

**Comment by b3spectacled** [comment]
Please see the FAQ: https://github.com/b3spectacled/modern-beta-fabric/wiki/FAQ
