### ISSUE TITLE
Version 4.0.2 (1.18.2) Crashes when clicking on "Modern Beta" world gen type.

### ISSUE THREAD

**Issue by xX420MCplayerXx** [b3spectacled/modern-beta-fabric#71]
[crash-2023-03-05_13.51.22-client.txt](https://github.com/b3spectacled/modern-beta-fabric/files/10892809/crash-2023-03-05_13.51.22-client.txt)

here is latest.log with the crash report.

**Comment by b3spectacled** [comment]
I'm investigating this, thanks.

**Comment by b3spectacled** [comment]
Can you try deleting the config files and see if that fixes the issue?

EDIT: Alternatively, I just released 4.0.3 which you can try out, should fix this crash as well.
