### ISSUE TITLE
Allow customizing the world.

### ISSUE THREAD

**Issue by MagmaSlime123** [b3spectacled/modern-beta-fabric#72]
Title. No world-related configs exist.

![2023-03-05_14 28 01](https://user-images.githubusercontent.com/51277766/222987054-6a9a18cf-94db-4566-937c-f6db3aa91329.png)

![image](https://user-images.githubusercontent.com/51277766/222987068-8191b3b6-6f18-4567-9d07-2a07fe800340.png)

**Comment by b3spectacled** [comment]
See #69
