### ISSUE TITLE
Pocket Edition "Old" world type

### ISSUE THREAD

**Issue by tyty5869** [b3spectacled/modern-beta-fabric#73]
I'm not sure if this the is place to ask, but I am on my hands and knees requesting that you add the Pocket Edition Old World Type to Modern Beta. This was the generation that was 256 x 256 blocks and had no caves. Unless I'm stupid, there is no way for me to be able to revisit the seeds I spent my childhood playing on.

**Comment by b3spectacled** [comment]
I don't know if I will add a limited map generation option (you could use the world border game rule as an alternative), but I will add a cave generation toggle for the upcoming 1.19.4 update.

**Comment by b3spectacled** [comment]
Closing since you can kinda emulate a closed world type using the island options with a square island shape.
