### ISSUE TITLE
Skylands preset gives error on server (Empty height range)

### ISSUE THREAD

**Issue by doubleaxes** [b3spectacled/modern-beta-fabric#75]
1.19.3 (fabric)
The server gives me these errors and times me out

[23:36:03] [Worker-Main-10/WARN]: Empty height range: [6 above bottom--1 absolute]
[23:36:04] [Worker-Main-10/WARN]: Empty height range: [136 absolute-0 below top]

how can I solve this issue?

**Comment by b3spectacled** [comment]
Can you provide the full output log when you try to connect?

**Comment by doubleaxes** [comment]
for now I cant recreate the same error

**Comment by b3spectacled** [comment]
If you can reproduce the error with the timeout, then please reopen with the full output log. The Empty height range warnings are a known issue and should have no effect on world generation.

**Comment by doubleaxes** [comment]
(this happend in a singleplayer world)I still have no log but when I try to locate a beta ocean biome (changed the biome provider to beta) the game freezes. Im not exactly sure If it is the same error but it is similar

**Comment by b3spectacled** [comment]
Oceans do not generate in Skylands worlds.

**Comment by doubleaxes** [comment]
yeah I figured that was the problem lol
