### ISSUE TITLE
(Suggestion) Generating different biomes in the skylands preset?

### ISSUE THREAD

**Issue by doubleaxes** [b3spectacled/modern-beta-fabric#76]
I don't know If this would be an different preset or just a config setting (1.19.3) but I think it would be great If we get different biomes in the skylands other than the ''Plains'' look. Maybe this could apply to other presets? Im not sure.

**Comment by b3spectacled** [comment]
Change `biomeProvider` setting, documentation here: https://github.com/b3spectacled/modern-beta-fabric/wiki/1.19-Biome-Settings#biomeprovider

**Comment by doubleaxes** [comment]
thanks it worked Im gonna try this with cave generation too lol
