### ISSUE TITLE
There isn't any customize button on "World Type: Modern Beta"

### ISSUE THREAD

**Issue by StepanKomis** [b3spectacled/modern-beta-fabric#77]
I have mod from curseForge.com I have fabric version and game version 1.19.3 I would like to use this mod, but I couldn't figure out why is this happening.
I can still use default settings but I want to plawith it for a little bit.
 Does somebody know what is wrong, or can somebody help?

**Comment by b3spectacled** [comment]
See #69

**Comment by StepanKomis** [comment]
> See #69
when I copy zipped file to resourspacks directory it wont show in in-game resourspacks folder. I didnt change anything at all, I just moved it out cuz my OS had some problem with it or whatever. Can you send it to me or help me with zipping it up, I don't know if it is my fault or if it just doesn't work

edit: I found out this is datapack not a resoursepack

**Comment by StepanKomis** [comment]
> See #69

Can I ask how can I change the settings?

**Comment by b3spectacled** [comment]
You're supposed to extract the folders from the .zip, pick one and then add it to the data packs list in-game. As for editing the settings, you need to open up the world preset file under `data\modern_beta\worldgen\world_preset` and edit the values there.

Edit: Instructions in the wiki: https://github.com/b3spectacled/modern-beta-fabric/wiki/1.19-Data-Packs
