### ISSUE TITLE
Modded ores don't spawn on Beta generation

### ISSUE THREAD

**Issue by BioOnPC** [b3spectacled/modern-beta-fabric#8]
I've created a few worlds with Tech Reborn and Astromine, and both of their sets of ores will not spawn on Beta generation. Other mods that affect cave generation, such as Cave Biomes, are working fully alongside this type of generation, and the ores spawn in normal terrain generation.

**Comment by b3spectacled** [comment]
Appears to be an issue with the datapack-based biomes the mod uses.  I'll look into workarounds.

**Comment by b3spectacled** [comment]
Partially fixed, Astromine should now be compatible.  Unfortunately Tech Reborn appears to inject its ores only into biomes supplied to the vanilla biome provider.  Since the biomes in this mod are not added to the default world type, they do not get TR's ores.

**Comment by b3spectacled** [comment]
Apologies for the lateness of this, I've only recently figured out how to get TR to work with the mod and added it to v1.0.8.  Thanks for your patience (if you're still waiting)!
