### ISSUE TITLE
how do i generate beta terrain with modern caves? (1.19.3) also do biome mods work? if so how?

### ISSUE THREAD

**Issue by yamiyugi13** [b3spectacled/modern-beta-fabric#80]

**Comment by b3spectacled** [comment]
1. To use modern cave carvers, you will have to edit each individual biome file from the data pack. If you're talking about noise caves, those have been removed as of 1.19.x and I currently have no plans of re-adding them.
2. I don't officially support vanilla biome generation, and by extension most biome mods that might use TerraBlender or something similar. What you can do is manually construct your own biome map by adding to the `voronoiPoints` list in the biome options, then using the `voronoi` biome provider.

**Comment by yamiyugi13** [comment]
if noise caves is the modern cave generator then  yes. how do i generate them in 1.18 then?

**Comment by b3spectacled** [comment]
They should be on by default. If not, then you can go into the world customization screen when creating a new world to toggle it.
