### ISSUE TITLE
Where's customise button in 1.19.3

### ISSUE THREAD

**Issue by ishikawa180** [b3spectacled/modern-beta-fabric#81]
<img width="1710" alt="Screenshot 2023-03-15 at 3 40 20 pm" src="https://user-images.githubusercontent.com/116607391/225312728-a19183f6-e85f-47f5-9a88-7ce62aca8447.png">

**Comment by ishikawa180** [comment]
Ive launched fresh build with only Fabric API, Cloth Config and Modern Beta, theres just no button for some reason

**Comment by ishikawa180** [comment]
It exists in 1.19.4 but not in 1.19.3 for some reason

**Comment by ishikawa180** [comment]
Setup: Apple MacBook Air M2, Prism Launcher
Ask if you need any more info :)

**Comment by b3spectacled** [comment]
Not implemented in 1.19.3, I just re-added it in 1.19.4.

**Comment by ishikawa180** [comment]
The problem is that i really want to have it in 1.19.3 as i play this version right now and also theres not a lot of mods transfered to 1.19.4 yet
I'll be very happy if you will update version 1.19.3, please!

**Comment by b3spectacled** [comment]
I will see whether backporting to 1.19.3 isn't too much trouble (vs. 1.19.3 -> 1.19.2 which contains much more changes under the hood).

**Comment by b3spectacled** [comment]
I've updated the 1.19.3 version to 6.0, the whole feature list is there. If you run into any problems, feel free to open a new issue.
