### ISSUE TITLE
cave generation

### ISSUE THREAD

**Issue by shawtyslikeamelody2** [b3spectacled/modern-beta-fabric#84]
this isnt an issue but i dont know where else to ask this, how do i get modern cave generation (carver and noise) with modern beta worlds like the 1.18.2 version had with its custom settings?

**Comment by b3spectacled** [comment]
Noise caves are removed as of 1.19.3 and later. I do not plan to re-implement at the moment. If you want to use current carver caves instead of the old one, that will require fiddling around with the biome JSON files in the data pack.
