### ISSUE TITLE
(1.19.3) Unable to use Beta Taiga or Snowy Taiga with custom settings in version 6.1 

### ISSUE THREAD

**Issue by taway1** [b3spectacled/modern-beta-fabric#87]
I'm trying to make a world with a blend of modern and beta biomes through the biome settings in the customization tab of the Modern Beta world preset. As the title mentions: the Beta Taiga and Snowy Taiga biomes are problematic. When attempting to generate a world with either biome, neither of them is present in the world. The other biomes are present in the world, regardless of if the Beta Taiga or Snowy Taiga biomes are present. In the settings, I use the following Voronoi points:

    {
      "biome": "modern_beta:beta_tundra",
      "oceanBiome": "minecraft:frozen_ocean",
      "deepOceanBiome": "minecraft:frozen_ocean",
      "temp": 0.0,
      "rain": 0.5
    },
    {
      "biome": "minecraft:snowy_taiga",
      "oceanBiome": "minecraft:frozen_ocean",
      "deepOceanBiome": "minecraft:frozen_ocean",
      "temp": -0.5,
      "rain": 0.4
    },
    {
      "biome": "minecraft:taiga",
      "oceanBiome": "minecraft:cold_ocean",
      "deepOceanBiome": "minecraft:cold_ocean",
      "temp": 0.25,
      "rain": 0.8
    },
    {
      "biome": "modern_beta:beta_plains",
      "oceanBiome": "minecraft:ocean",
      "deepOceanBiome": "minecraft:ocean",
      "temp": 1.0,
      "rain": 0.4
    },
    {
      "biome": "modern_beta:beta_forest",
      "oceanBiome": "minecraft:ocean",
      "deepOceanBiome": "minecraft:ocean",
      "temp": 0.7,
      "rain": 0.8
    },
    {
      "biome": "minecraft:swamp",
      "oceanBiome": "minecraft:lukewarm_ocean",
      "deepOceanBiome": "minecraft:lukewarm_ocean",
      "temp": 0.8,
      "rain": 0.9
    },
    {
      "biome": "modern_beta:beta_desert",
      "oceanBiome": "minecraft:warm_ocean",
      "deepOceanBiome": "minecraft:warm_ocean",
      "temp": 1.0,
      "rain": 0.0
    },
    {
      "biome": "modern_beta:beta_rainforest",
      "oceanBiome": "minecraft:lukewarm_ocean",
      "deepOceanBiome": "minecraft:lukewarm_ocean",
      "temp": 1.0,
      "rain": 1.0
    },
    {
      "biome": "minecraft:jungle",
      "oceanBiome": "minecraft:warm_ocean",
      "deepOceanBiome": "minecraft:warm_ocean",
      "temp": 0.95,
      "rain": 0.9
    }

Aside from the changed biome roster and setting the biome provider to "voronoi", it's the same as the default settings. The example shows the Snowy Taiga biome. When using the Beta Taiga, I change the temperature to 0.0 and the downfall to 0.5 (the values of each parameter I retrieved from the .json file for the biome).

**Comment by b3spectacled** [comment]
There are two things you should try. First, you should use non-negative values for temperature/rainfall; for biome placement, the mod uses the Beta climate noise generator which clamps the values to a range of 0.0 to 1.0. Next, in the case of the Beta Taiga biome, you use the values 0.0/0.5, which is shared with the Beta Tundra biome entry in your list. If two or more entries share the same climate values, then the first one in the list will be picked. The second point is not made clear in the wiki, so I'll update it.

Also don't worry about the climate values matching what's listed in the biome .json files. In the .json files, those values are used to just to control biome colors and whether it rains/snows. For the climate values of a voronoi point, you can pick whichever values that make sense relative to the other biome entries.

**Comment by taway1** [comment]
All works well now. Thank you.

**Comment by b3spectacled** [comment]
Great to hear, thanks for reporting.
