### ISSUE TITLE
Trying to create a beta/alpha/in/infdev biome using "Single Biome"/"Caves"/"Floating Island" generators spams console

### ISSUE THREAD

**Issue by helpimnotdrowning** [b3spectacled/modern-beta-fabric#9]
Trying to load any biome introduced by this mod with the buffet generators will show the chunk generation square thing correctly up to 100%, the player will join the singleplayer world, but once it gets to the 
`Saving chunks for level 'ServerLevel[World Name]'/minecraft:overworld` 
part, it spams
`Received invalid biome id: -1`.
The server workaround of deleting the "region" folder doesn't fix this.

[Log file](https://github.com/b3spectacled/modern-beta-fabric/files/5599880/latest.log)

MC version: 1.16.4
Mod version: 1.0.2

**Comment by b3spectacled** [comment]
Current workaround is to add the datapack before world creation.  The mod's biomes aren't meant to be used for these world types so there will be various issues.

**Comment by b3spectacled** [comment]
Fixed with release v1.0.3.
